blank_issues_enabled: false
contact_links:
  - name: â“Ask a Question
    url: https://github.com/telegram-bot-sdk/telegram-bot-sdk/discussions/new?category=q-a
    about: 'Ask the community for help'
  - name: ğŸš€ Feature Request
    url: https://github.com/telegram-bot-sdk/telegram-bot-sdk/discussions/new?category=ideas
    about: 'Share ideas for new features'
  - name: ğŸ’¬ PHP Chat Community on Slack
    url: https://phpchat.co
    about: 'For any help and support from the community on Slack'
  - name: ğŸ—£ PHP Chat Community on Telegram
    url: https://t.me/PHPChatCo
    about: 'For any help and support from the community on Telegram'
  - name: ğŸ“– Documentation Issue
    url: https://github.com/telegram-bot-sdk/website
    about: 'For documentation issues, open a pull request at the telegram-bot-sdk/website repository'
    
  
