blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ PHP Chat Community on Slack
    url: https://phpchat.co
    about: 'For any help and support from the community on Slack'
  - name: ğŸ—£ PHP Chat Community on Telegram
    url: https://t.me/PHPChatCo
    about: 'For any help and support from the community on Telegram'
  - name: â“ Support Questions & Other
    url: https://github.com/telegram-bot-sdk/.github/blob/master/SUPPORT.md
    about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
  - name: ğŸ“– Documentation Issue
    url: https://github.com/telegram-bot-sdk/docs
    about: 'For documentation issues, open a pull request at the telegram-bot-sdk/docs repository'
